config/routes.rb
Rails.application.routes.draw do

  scope module: 'authenticated' do
    resources :district_superintendents

    resources :class_enrollments

    resources :school_classes

    resources :teachers

    resources :schools

    resources :districts

    resources :parents

    resources :students
  end

  devise_for :users

  root 'home#index'

end

app/models/district_superintendent.rb
class DistrictSuperintendent < ActiveRecord::Base
  belongs_to :user
  belongs_to :district
end

app/controllers/authenticated/authenticated_controller.rb
class Authenticated::AuthenticatedController < ApplicationController
  include Pundit
  before_action :authenticate_user!
  after_action :verify_policy_scoped, :only => [:index, :show, :edit, :update, :destroy]
  after_action :verify_authorized, :except => :index

end

app/controllers/authenticated/class_enrollments_controller.rb
class Authenticated::Authenticated::ClassEnrollmentsController < Authenticated::AuthenticatedController
  before_action :set_class_enrollment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @class_enrollments = ClassEnrollment.all
    respond_with(@class_enrollments)
  end

  def show
    respond_with(@class_enrollment)
  end

  def new
    @class_enrollment = ClassEnrollment.new
    respond_with(@class_enrollment)
  end

  def edit
  end

  def create
    @class_enrollment = ClassEnrollment.new(class_enrollment_params)
    @class_enrollment.save
    respond_with(@class_enrollment)
  end

  def update
    @class_enrollment.update(class_enrollment_params)
    respond_with(@class_enrollment)
  end

  def destroy
    @class_enrollment.destroy
    respond_with(@class_enrollment)
  end

  private
    def set_class_enrollment
      @class_enrollment = ClassEnrollment.find(params[:id])
    end

    def class_enrollment_params
      params.require(:class_enrollment).permit(:school_class_id, :student_id, :grade)
    end
end

app/controllers/authenticated/district_superintendents_controller.rb
class Authenticated::DistrictSuperintendentsController < Authenticated::AuthenticatedController
  before_action :set_district_superintendent, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @district_superintendents = DistrictSuperintendent.all
    respond_with(@district_superintendents)
  end

  def show
    respond_with(@district_superintendent)
  end

  def new
    @district_superintendent = DistrictSuperintendent.new
    respond_with(@district_superintendent)
  end

  def edit
  end

  def create
    @district_superintendent = DistrictSuperintendent.new(district_superintendent_params)
    @district_superintendent.save
    respond_with(@district_superintendent)
  end

  def update
    @district_superintendent.update(district_superintendent_params)
    respond_with(@district_superintendent)
  end

  def destroy
    @district_superintendent.destroy
    respond_with(@district_superintendent)
  end

  private
    def set_district_superintendent
      @district_superintendent = DistrictSuperintendent.find(params[:id])
    end

    def district_superintendent_params
      params.require(:district_superintendent).permit(:name, :district_id, :user_id)
    end
end

app/controllers/authenticated/districts_controller.rb
class Authenticated::DistrictsController < Authenticated::AuthenticatedController
  before_action :set_district, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @districts = District.all
    respond_with(@districts)
  end

  def show
    respond_with(@district)
  end

  def new
    @district = District.new
    respond_with(@district)
  end

  def edit
  end

  def create
    @district = District.new(district_params)
    @district.save
    respond_with(@district)
  end

  def update
    @district.update(district_params)
    respond_with(@district)
  end

  def destroy
    @district.destroy
    respond_with(@district)
  end

  private
    def set_district
      @district = District.find(params[:id])
    end

    def district_params
      params.require(:district).permit(:name)
    end
end

app/controllers/authenticated/parents_controller.rb
class Authenticated::ParentsController < Authenticated::AuthenticatedController
  before_action :set_parent, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @parents = Parent.all
    respond_with(@parents)
  end

  def show
    respond_with(@parent)
  end

  def new
    @parent = Parent.new
    respond_with(@parent)
  end

  def edit
  end

  def create
    @parent = Parent.new(parent_params)
    @parent.save
    respond_with(@parent)
  end

  def update
    @parent.update(parent_params)
    respond_with(@parent)
  end

  def destroy
    @parent.destroy
    respond_with(@parent)
  end

  private
    def set_parent
      @parent = Parent.find(params[:id])
    end

    def parent_params
      params.require(:parent).permit(:name, :user_id)
    end
end

app/controllers/authenticated/school_classes_controller.rb
class Authenticated::SchoolClassesController < Authenticated::AuthenticatedController
  before_action :set_school_class, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @school_classes = SchoolClass.all
    respond_with(@school_classes)
  end

  def show
    respond_with(@school_class)
  end

  def new
    @school_class = SchoolClass.new
    respond_with(@school_class)
  end

  def edit
  end

  def create
    @school_class = SchoolClass.new(school_class_params)
    @school_class.save
    respond_with(@school_class)
  end

  def update
    @school_class.update(school_class_params)
    respond_with(@school_class)
  end

  def destroy
    @school_class.destroy
    respond_with(@school_class)
  end

  private
    def set_school_class
      @school_class = SchoolClass.find(params[:id])
    end

    def school_class_params
      params.require(:school_class).permit(:name, :school_id, :teacher_id)
    end
end

app/controllers/authenticated/schools_controller.rb
class Authenticated::SchoolsController < Authenticated::AuthenticatedController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @schools = School.all
    respond_with(@schools)
  end

  def show
    respond_with(@school)
  end

  def new
    @school = School.new
    respond_with(@school)
  end

  def edit
  end

  def create
    @school = School.new(school_params)
    @school.save
    respond_with(@school)
  end

  def update
    @school.update(school_params)
    respond_with(@school)
  end

  def destroy
    @school.destroy
    respond_with(@school)
  end

  private
    def set_school
      @school = School.find(params[:id])
    end

    def school_params
      params.require(:school).permit(:name, :district_id)
    end
end

app/controllers/authenticated/students_controller.rb
class Authenticated::StudentsController < Authenticated::AuthenticatedController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @students = policy_scope(Student)
    respond_with(@students)
  end

  def show
    respond_with(@student)
  end

  def new
    @student = Student.new
    authorize @student
    respond_with(@student)
  end

  def edit
  end

  def create
    @student = Student.new(student_params)
    @student.save
    respond_with(@student)
  end

  def update
    @student.update(student_params)
    respond_with(@student)
  end

  def destroy
    @student.destroy
    respond_with(@student)
  end

  private
    def set_student
      # We use find_by_id instead of find to avoid raising an ActiveRecord::RecordNotFound, instead
      # we call not_found defined on our application_controller to render our generic 404 form.
      @student = policy_scope(Student).find_by_id(params[:id]) or not_found
      authorize @student
    end

    def student_params
      params.require(:student).permit(:name, :user_id, :parent_id)
    end
end

app/controllers/authenticated/teachers_controller.rb
class Authenticated::TeachersController < Authenticated::AuthenticatedController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @teachers = policy_scope(Teacher)
    authorize @teachers
    respond_with(@teachers)
  end

  def show
    respond_with(@teacher)
  end

  def new
    @teacher = Teacher.new
    authorize @teacher
    respond_with(@teacher)
  end

  def edit
  end

  def create
    @teacher = Teacher.new(teacher_params)
    @teacher.save
    respond_with(@teacher)
  end

  def update
    @teacher.update(teacher_params)
    respond_with(@teacher)
  end

  def destroy
    @teacher.destroy
    respond_with(@teacher)
  end

  private
    def set_teacher
      @teacher = policy_scope(Teacher).find_by_id(params[:id]) or not_found
      authorize @teacher
    end

    def teacher_params
      params.require(:teacher).permit(:name, :school_id, :user_id)
    end
end

app/controllers/district_superintendents_controller.rb
class DistrictSuperintendentsController < ApplicationController
  before_action :set_district_superintendent, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @district_superintendents = DistrictSuperintendent.all
    respond_with(@district_superintendents)
  end

  def show
    respond_with(@district_superintendent)
  end

  def new
    @district_superintendent = DistrictSuperintendent.new
    respond_with(@district_superintendent)
  end

  def edit
  end

  def create
    @district_superintendent = DistrictSuperintendent.new(district_superintendent_params)
    @district_superintendent.save
    respond_with(@district_superintendent)
  end

  def update
    @district_superintendent.update(district_superintendent_params)
    respond_with(@district_superintendent)
  end

  def destroy
    @district_superintendent.destroy
    respond_with(@district_superintendent)
  end

  private
    def set_district_superintendent
      @district_superintendent = DistrictSuperintendent.find(params[:id])
    end

    def district_superintendent_params
      params.require(:district_superintendent).permit(:name, :district_id, :user_id)
    end
end

app/helpers/district_superintendents_helper.rb
module DistrictSuperintendentsHelper
end

app/views/authenticated/district_superintendents/_form.html.erb
<%= form_for(@district_superintendent) do |f| %>
  <% if @district_superintendent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@district_superintendent.errors.count, "error") %> prohibited this district_superintendent from being saved:</h2>

      <ul>
      <% @district_superintendent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :district_id %><br>
    <%= f.number_field :district_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authenticated/district_superintendents/edit.html.erb
<h1>Editing district_superintendent</h1>

<%= render 'form' %>

<%= link_to 'Show', @district_superintendent %> |
<%= link_to 'Back', district_superintendents_path %>

app/views/authenticated/district_superintendents/index.html.erb
<h1>Listing district_superintendents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>District</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @district_superintendents.each do |district_superintendent| %>
      <tr>
        <td><%= district_superintendent.name %></td>
        <td><%= district_superintendent.district_id %></td>
        <td><%= district_superintendent.user_id %></td>
        <td><%= link_to 'Show', district_superintendent %></td>
        <td><%= link_to 'Edit', edit_district_superintendent_path(district_superintendent) %></td>
        <td><%= link_to 'Destroy', district_superintendent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New District superintendent', new_district_superintendent_path %>

app/views/authenticated/district_superintendents/new.html.erb
<h1>New district_superintendent</h1>

<%= render 'form' %>

<%= link_to 'Back', district_superintendents_path %>

app/views/authenticated/district_superintendents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @district_superintendent.name %>
</p>

<p>
  <strong>District:</strong>
  <%= @district_superintendent.district_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @district_superintendent.user_id %>
</p>

<%= link_to 'Edit', edit_district_superintendent_path(@district_superintendent) %> |
<%= link_to 'Back', district_superintendents_path %>